### ISSUE TITLE
higher results with respect to the matching networks

### ISSUE THREAD

**Issue by d12306** [icoz69/DeepEMD#17]
hi, @icoz69 , thanks for releasing the code! I am quite surprising that the results of some of the baselines are much more higher than that reported in the original paper, such as matching network, i.e., 63.08% in deepemd compared to 43% in nips paper, is it because you change the backbone to resnet12?

Looking forward to your reply.

**Comment by icoz69** [comment]
hello, this is mainly due to the training paradigm. early works only use meta-training to optimize the model that episodically sample a task to train the model. Many recent works find that directly 'pre-train'  the model with all training classes can quickly learn useful backbone as an initial step before meta-training, So, all these baselines are trained by two steps. Note that the pre-trianing here does not indicate training with extra data. it is only a training option given the same amount of training data.

**Comment by d12306** [comment]
great, thanks for your explanation!
