### ISSUE TITLE
Pretrain model overfitting 

### ISSUE THREAD

**Issue by zgjslc** [icoz69/DeepEMD#46]
Thanks for your exciting work! When I pretrain miniimagenet , I notice that the train acc up to 92% , while the val acc only 62% , whether it has being overrfitting? or should i check my code?

**Comment by icoz69** [comment]
Hi &nbsp;, this looks normal.







------------------ Original ------------------
From: zgjslc ***@***.***&gt;
Date: Sat,Dec 4,2021 3:31 PM
To: icoz69/DeepEMD ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [icoz69/DeepEMD] Pretrain model overfitting  (Issue #46)





 
Thanks for your exciting work! When I pretrain miniimagenet , I notice that the train acc up to 92% , while the val acc only 62% , whether it has being overrfitting? or should i check my code?
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
